urls.py
from django.conf.urls.defaults import *

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    (r'^$', 'scorekeeper.views.index'),
    (r'^game/(?P<game_slug>[-\w]+)/$', 'scorekeeper.views.game_detail'),
    (r'^ajax_game/(?P<game_slug>[-\w]+)/$', 'scorekeeper.views.ajax_game_detail'),
    (r'^level/(?P<level_slug>[-\w]+)/$', 'scorekeeper.views.level_detail'),
    (r'^player/(?P<player_slug>[-\w]+)/$', 'scorekeeper.views.player_detail'),
    (r'^score/$', 'scorekeeper.views.score'),
    # Uncomment the admin/doc line below and add 'django.contrib.admindocs' 
    # to INSTALLED_APPS to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    (r'^admin/', include(admin.site.urls)),
)

scorekeeper/models.py
from django.db import models
from django.conf import settings
from django.utils.encoding import smart_str    

class Game(models.Model):
    slug = models.SlugField(max_length=80, unique=True)
    name = models.CharField(max_length=80)
    description = models.TextField()
    nbScoreSubmitted = models.PositiveIntegerField(default=0);
    def __unicode__(self):
        return self.name
    @models.permalink
    def get_absolute_url(self):
        return ('scorekeeper.views.game_detail', [smart_str(self.slug)])
    
class Level(models.Model):
    slug = models.SlugField(max_length=80, unique=True)
    name = models.CharField(max_length=80)
    game=models.ForeignKey(Game)
    def __unicode__(self):
        return self.name
    @models.permalink
    def get_absolute_url(self):
        return ('scorekeeper.views.level_detail', [smart_str(self.slug)])
    def sorted_scores(self):
        return self.score_set.all().order_by('-score')
    def cleanup(self):
        if self.score_set.count() > settings.SCORESERVER_MAX_SCORE_TO_KEEP:
            for scoreToDelete in self.score_set.all().order_by('-score')[settings.SCORESERVER_MAX_SCORE_TO_KEEP:]:
                scoreToDelete.delete()

class Player(models.Model):
    slug = models.SlugField(max_length=80, unique=True)
    secret = models.SlugField(max_length=80)
    registered = models.BooleanField(default=False)
    @models.permalink
    def get_absolute_url(self):
        return ('scorekeeper.views.player_detail', [smart_str(self.slug)])
    def __unicode__(self):
        return self.slug
    def sorted_scores(self):
        return self.score_set.all().order_by('-level__name', '-score')
    @staticmethod
    def cleanup():
        for player in Player.objects.annotate(num_scores = models.Count('score')).filter(num_scores = 0, registered=False):
            player.delete()

class Score(models.Model):
    player = models.ForeignKey(Player)
    level = models.ForeignKey(Level)
    score = models.IntegerField()
    def __unicode__(self):
        return self.level.name + ': ' + self.player.slug + ' = ' + smart_str(self.score )    

scorekeeper/views.py
from django.http import HttpResponse
from django.template import RequestContext, loader
from django.views.generic import list_detail
from scorekeeper.models import Game, Level, Player, Score
import re

def index(request):
    games = Game.objects.all().order_by('-name')
    t = loader.get_template('scorekeeper/templates/index.html')
    c = RequestContext(request, {
        'games' : games,
    })
    return HttpResponse(t.render(c))
    
def game_detail(request, game_slug):
    return list_detail.object_detail( request, queryset= Game.objects.all(), slug=game_slug, slug_field='slug', template_name='scorekeeper/templates/game_detail.html'  )

def ajax_game_detail(request, game_slug):
    return list_detail.object_detail( request, queryset= Game.objects.all(), slug=game_slug, slug_field='slug', template_name='scorekeeper/templates/ajax_game_detail.html'  )
    
def level_detail(request, level_slug):
    return list_detail.object_detail( request, queryset= Level.objects.all(), slug=level_slug, slug_field='slug', template_name='scorekeeper/templates/level_detail.html'  )

def player_detail(request, player_slug):
    return list_detail.object_detail( request, queryset= Player.objects.all(), slug=player_slug, slug_field='slug', template_name='scorekeeper/templates/player_detail.html'  )

check_slug_re = re.compile(r'^[-\w]+$')
def checkSlug(s):
    return check_slug_re.search(s)

def score(request):
    #create or update score
    level = Level.objects.get(slug=request.REQUEST['level'])
    playerName = request.REQUEST['player']
    if not checkSlug(playerName):
        return HttpResponse("player name must contain only letters, numbers, underscores or hyphens")
        
    player, isNewPlayer = Player.objects.get_or_create(slug=playerName, defaults={'secret':request.REQUEST['secret']})
    if not isNewPlayer and player.secret != request.REQUEST['secret']:
        return HttpResponse("invalid player secret")
    score, isNewScore = Score.objects.get_or_create( level = level, player = player, defaults={'score':request.REQUEST['score']} )
    if not isNewScore:
        score.score = max( int( request.REQUEST['score'] ), int( score.score ) )
        score.save()
    level.game.nbScoreSubmitted += 1
    level.game.save()
    #cleanup
    level.cleanup()
    Player.cleanup()
    return HttpResponse("score saved")

scorekeeper/templates/ajax_game_detail.html
<table>
{% for level in object.level_set.all %}
    <tr><th colspan="2">{{ level.name }}</th></tr>
    
    {% for score in level.sorted_scores %}
    <tr>
        <td>{{ score.score }}</td><td>{{ score.player.slug }}</td>
    </tr>
    {% endfor %}
{% endfor %}
</table>

scorekeeper/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Scoreserver{% endblock %}</title>
    <style type="text/css">
    body {
        background-color:black;
        color:white;
        font-family:"Courier New", Courier, monospace;
        font-weight:bold;
    }
    h1 {
        text-align:center;
    }
    table {
        margin-left:auto;
        margin-right:auto;
        border-collapse:collapse;
    }
    table, th, td {
        padding:10px;
    }
    a:link {
        color:red;
        text-decoration:none;
    }
    a:visited {
        color:red;
        text-decoration:none;
    }
    a:hover {
        color:red;
        text-decoration:underline;
    }
    a:active {
        color:red;
        text-decoration:underline;
    } 
    </style>

</head>

<body>
    <div id="content">
        {% block content %}{% endblock %}
    </div>
</body>
</html>


scorekeeper/templates/game_detail.html
{% extends "base.html" %}

{% block content %}
    <h1>{{ object.name }}</h1>
    <p>{{ object.description }}</p>
    <table>
        {% for level in object.level_set.all %}
            <tr>
                <td><a href="{{ level.get_absolute_url }}">{{ level.name }}</td>
            </tr>
        {% endfor %}
    </table>
    <p>{{ object.nbScoreSubmitted  }} scores submitted.</p>
    
{% endblock %}


scorekeeper/templates/index.html
{% extends "base.html" %}

{% block content %}
    <h1>Games</h1>
    <table>
        {% for game in games %}
        <td>
            <a href="{{ game.get_absolute_url }}">{{ game.name }}</a>
        </td>
        {% endfor %}
    </table>
{% endblock %}


scorekeeper/templates/level_detail.html
{% extends "base.html" %}

{% block content %}
    <h1> <a href="{{ object.game.get_absolute_url }}">{{ object.game.name }}</a>: {{ object.name }}</h1>
    
    <table>
    {% for score in object.sorted_scores %}
    <tr>
        <td>{{ score.score }}</td><td><a href="{{ score.player.get_absolute_url }}">{{ score.player.slug }}</a></td>
    </tr>
    {% endfor %}
    </table>
    
{% endblock %}

scorekeeper/templates/player_detail.html
{% extends "base.html" %}

{% block content %}
    <h1>{{ object.slug }}</h1>
    <table>
        {% for score in object.sorted_scores %}
            <tr>
                <td><a href="{{ score.level.game.get_absolute_url }}">{{ score.level.game.name }}</td>
                <td><a href="{{ score.level.get_absolute_url }}">{{ score.level.name }}</td>
                <td>{{ score.score }}</td>
            </tr>
        {% endfor %}
    </table>
    
{% endblock %}